import { executeTestSuite } from './executionSandbox.js';
import { writeStatelessSelfHostedTool, verifySelfHostedEntry } from './selfHosting.js';
import type { ToolDomain } from '../types.js';

const AXIOM_URL = process.env.AXIOM_URL || 'http://127.0.0.1:3198';
const TIMEOUT_MS = Number(process.env.AXIOM_TIMEOUT_MS || 180000);

export async function axiomReachable(): Promise<boolean> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 2000);
  try {
    const res = await fetch(`${AXIOM_URL}/api/health`, { signal: controller.signal });
    return res.ok;
  } catch { return false; } finally { clearTimeout(timer); }
}

export async function integrateAxiomTool(
  name: string,
  domain: ToolDomain,
  prompt: string,
  refSuite: string
): Promise<{ ok: boolean; selfHosted?: any; error?: string }> {
  // 1. Build via Axiom
  const buildRes = await fetch(`${AXIOM_URL}/api/axiom/build`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ name, domain, prompt, refSuite }),
    signal: AbortSignal.timeout(TIMEOUT_MS),
  });
  if (!buildRes.ok) return { ok: false, error: `Axiom build failed: ${buildRes.status}` };
  const build = await buildRes.json();
  if (!build.ok) return { ok: false, error: build.errors?.join(' | ') || 'Axiom internal build error' };

  // 2. Verify with Recourse's own sandbox
  const suiteResult = executeTestSuite(build.sourceCode, refSuite);
  if (!suiteResult.passed) {
    return { ok: false, error: `Verification failed: ${suiteResult.testDetails.join('; ')}` };
  }

  // 3. Write self-hosted tool
  const writeRes = writeStatelessSelfHostedTool({
    name,
    domain,
    entrypointName: name,
    sourceCode: build.sourceCode,
    testSuiteCode: refSuite,
    summary: `Generated by Axiom (engine: ${build.engine})`,
  });
  if (writeRes.success === false) return { ok: false, error: writeRes.error };

  // 4. Final verify-entry check
  await verifySelfHostedEntry(writeRes.entry);
  return { ok: true, selfHosted: writeRes.entry };
}
