/**
 * v1Client.generated.ts — GENERATED by `src/lib/openapiV1.ts`.
 *
 * DO NOT EDIT BY HAND. Regenerate with `npx tsx scripts/gen-v1-client.ts`.
 * The client is derived from V1_ROUTES, so it stays in lockstep with the
 * served OpenAPI document and the router.
 */

export interface V1ClientOptions {
  baseUrl: string;
  apiKey?: string;
  fetchImpl?: typeof fetch;
}

export interface V1Response<T = unknown> {
  ok: boolean;
  status: number;
  data: T;
}

export interface V1Client {
  status: () => Promise<V1Response>;
  me: () => Promise<V1Response>;
  plans: () => Promise<V1Response>;
  usage: (args?: { query?: Record<string, string | number | boolean | undefined> }) => Promise<V1Response>;
  keys: {
    list: () => Promise<V1Response>;
    create: (args?: { body?: Record<string, unknown> }) => Promise<V1Response>;
    rotate: (args: { id: string }) => Promise<V1Response>;
    revoke: (args: { id: string }) => Promise<V1Response>;
  };
  billing: {
    checkout: (args?: { body?: Record<string, unknown> }) => Promise<V1Response>;
    webhook: () => Promise<V1Response>;
  };
  outcome: {
    record: (args?: { body?: Record<string, unknown> }) => Promise<V1Response>;
    latest: () => Promise<V1Response>;
  };
  learner: {
    episode: (args?: { body?: Record<string, unknown> }) => Promise<V1Response>;
  };
}

function buildUrl(baseUrl: string, path: string): string {
  return baseUrl.replace(/\/+$/, '') + path;
}

export function createV1Client(options: V1ClientOptions): V1Client {
  const fetchImpl = options.fetchImpl ?? fetch;

  const request = async (
    method: string,
    path: string,
    body?: unknown,
    query?: Record<string, unknown>,
  ): Promise<V1Response> => {
    let url = buildUrl(options.baseUrl, path);
    if (query) {
      const search = new URLSearchParams();
      for (const [k, v] of Object.entries(query)) {
        if (v !== undefined && v !== null) search.set(k, String(v));
      }
      const qs = search.toString();
      if (qs) url += (url.includes('?') ? '&' : '?') + qs;
    }
    const headers: Record<string, string> = { 'Content-Type': 'application/json' };
    if (options.apiKey) headers['x-api-key'] = options.apiKey;
    const res = await fetchImpl(url, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    let data: unknown = null;
    const text = await res.text();
    try {
      data = text ? JSON.parse(text) : null;
    } catch {
      data = text;
    }
    return { ok: res.ok, status: res.status, data };
  };

  return {
    status: () => request('GET', `/v1/status`, undefined, undefined),
    me: () => request('GET', `/v1/me`, undefined, undefined),
    plans: () => request('GET', `/v1/plans`, undefined, undefined),
    usage: (args) => request('GET', `/v1/usage`, undefined, args?.query),
    keys: {
      list: () => request('GET', `/v1/keys`, undefined, undefined),
      create: (args) => request('POST', `/v1/keys`, args?.body, undefined),
      rotate: (args) => request('POST', `/v1/keys/${encodeURIComponent(String(args.id))}/rotate`, undefined, undefined),
      revoke: (args) => request('DELETE', `/v1/keys/${encodeURIComponent(String(args.id))}`, undefined, undefined),
    },
    billing: {
      checkout: (args) => request('POST', `/v1/billing/checkout`, args?.body, undefined),
      webhook: () => request('POST', `/v1/billing/webhook`, undefined, undefined),
    },
    outcome: {
      record: (args) => request('POST', `/v1/outcome`, args?.body, undefined),
      latest: () => request('GET', `/v1/outcome`, undefined, undefined),
    },
    learner: {
      episode: (args) => request('POST', `/v1/learner/episode`, args?.body, undefined),
    },
  };
}
