/**
 * Research Pipeline — produces a structured research brief for a business.
 *
 * Inputs:
 *   - Business profile (from businessProfile.ts)
 *   - Local document ingestion (README, marketing plans, pricing docs)
 *   - Web research (fetch against public URLs)
 *
 * Output:
 *   - research-brief.json in data/business-profiles/<slug>/
 *
 * Honest limits:
 *   - Web research via local fetch is shallow. Qwen 4B does not
 *     produce deep competitive intelligence. The brief is a starting point.
 *   - All claims are labeled [UNVERIFIED] until a human confirms them.
 *   - Competitor pricing is never scraped from competitor pages — only
 *     operator-supplied data goes into pricing claims.
 */

import { z } from 'zod';
import fs from 'node:fs';
import path from 'node:path';

// --- Output schemas -----------------------------------------------------------

export const CompetitorEntry = z.object({
  name: z.string(),
  tagline: z.string(),
  website: z.string().url().or(z.literal('')),
  positioning: z.string(),
  strengths: z.array(z.string()),
  weaknesses: z.array(z.string()),
  pricing: z.string().optional(),
  // How confident are we in this data? set by the pipeline based on sources.
  confidence: z.enum(['high', 'medium', 'low']).default('low'),
  source: z.string(),
});

export const KeywordOpportunity = z.object({
  phrase: z.string(),
  intent: z.enum(['informational', 'navigational', 'transactional', 'commercial']),
  difficulty: z.enum(['easy', 'medium', 'hard']).default('medium'),
  volumeHint: z.string().optional(), // "estimated 100-1k/mo" — never precise numbers from a 4B model
  notes: z.string().optional(),
});

export const ContentGap = z.object({
  topic: z.string(),
  whyItMatters: z.string(),
  competingContent: z.string(),
});

export const PositioningOption = z.object({
  framing: z.string(),
  tagline: z.string(),
  targetSegment: z.string(),
  risks: z.array(z.string()),
  confidence: z.enum(['high', 'medium', 'low']).default('low'),
});

export const MarketSizing = z.object({
  estimate: z.string(), // "hundreds of labs nationally" — never a precise number
  basis: z.string(),
  caveats: z.array(z.string()),
});

export const ResearchBrief = z.object({
  generatedAt: z.string().datetime(),
  businessSlug: z.string(),
  profileStage: z.string(),
  competitorLandscape: z.array(CompetitorEntry),
  keywordOpportunities: z.array(KeywordOpportunity),
  contentGaps: z.array(ContentGap),
  positioningOptions: z.array(PositioningOption),
  marketSizing: MarketSizing.optional(),
  localDocumentsIngested: z.array(z.string()),
  webSources: z.array(z.string()),
  disclaimer: z.string(),
  operatorNotes: z.string().optional(),
});
export type ResearchBriefT = z.infer<typeof ResearchBrief>;

// --- Config -----------------------------------------------------------------

const DEFAULT_TIMEOUT_MS = 10_000;

export interface ResearchPipelineConfig {
  timeoutMs?: number;
  maxWebSources?: number;
  localDocExtensions?: string[];
}

export const DEFAULT_CONFIG: Required<ResearchPipelineConfig> = {
  timeoutMs: DEFAULT_TIMEOUT_MS,
  maxWebSources: 5,
  localDocExtensions: ['.md', '.txt', '.yaml', '.yml', '.json'],
};

const DISLAIMER = `[LEGACY DISCLAIMER] This research brief was generated by a 4B parameter model. It is a starting point for your review, NOT ground truth. All competitor claims, market sizing estimates, and keyword volumes require independent verification by a human. Do not publish any claim from this brief without confirming it first.`;

const OPERATOR_NOTES =
  'Edit this field after reviewing the brief. Record which competitor data you verified, which claims you rejected, and any positioning decisions you made.';

// --- Local document ingestion -----------------------------------------------

export interface IngestResult {
  filename: string;
  content: string;
  size: number;
}

export function ingestLocalDocuments(
  repoPath: string,
  extensions: string[] = DEFAULT_CONFIG.localDocExtensions,
): IngestResult[] {
  if (!fs.existsSync(repoPath)) return [];

  const results: IngestResult[] = [];

  function walk(dir: string, depth: number = 0): void {
    if (depth >= 3) return; // don't recurse past 3 levels deep
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name === 'node_modules' || entry.name === '.git' || entry.name === '__pycache__') continue;
      if (entry.isDirectory()) {
        walk(path.join(dir, entry.name), depth + 1);
      } else if (entry.isFile() && extensions.some((ext) => entry.name.endsWith(ext))) {
        const filePath = path.join(dir, entry.name);
        try {
          const stat = fs.statSync(filePath);
          if (stat.size > 500_000) continue; // skip files > 500KB
          const content = fs.readFileSync(filePath, 'utf8');
          const rel = path.relative(repoPath, filePath);
          results.push({ filename: rel.split(path.sep).join('/'), content, size: stat.size });
        } catch {
          // skip files that can't be read
        }
      }
    }
  }

  walk(repoPath);
  return results;
}

export function extractRelevantSnippets(
  docs: IngestResult[],
  keywords: string[],
  maxSnippets: number = 20,
): string[] {
  const snippets: string[] = [];
  for (const doc of docs) {
    const lines = doc.content.split('\n');
    for (const line of lines) {
      const lower = line.toLowerCase();
      if (keywords.some((kw) => lower.includes(kw.toLowerCase())) && line.trim().length > 20) {
        snippets.push(`[${doc.filename}] ${line.trim().slice(0, 200)}`);
        if (snippets.length >= maxSnippets) break;
      }
    }
    if (snippets.length >= maxSnippets) break;
  }
  return snippets;
}

// --- Web research -----------------------------------------------------------

export interface WebFetchResult {
  url: string;
  title: string;
  content: string;
  error?: string;
}

export async function fetchWebPage(
  url: string,
  timeoutMs: number = DEFAULT_TIMEOUT_MS,
): Promise<WebFetchResult> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const res = await fetch(url, {
      signal: controller.signal,
      headers: {
        'User-Agent':
          'Mozilla/5.0 (compatible; RecourseResearchBot/1.0; +https://github.com)',
        Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
      },
      redirect: 'follow',
    });
    clearTimeout(timer);

    if (!res.ok) {
      return { url, title: '', content: '', error: `HTTP ${res.status}` };
    }

    const text = await res.text();
    const title = extractTitle(text);
    const content = stripHtml(text).slice(0, 3000); // truncate to 3k chars

    return { url, title, content };
  } catch (err) {
    clearTimeout(timer);
    const msg = err instanceof Error ? err.message : String(err);
    if (msg.includes('aborted')) {
      return { url, title: '', content: '', error: 'Timeout' };
    }
    return { url, title: '', content: '', error: msg };
  }
}

function extractTitle(html: string): string {
  const match = html.match(/<title[^>]*>([^<]+)<\/title>/i);
  return match ? match[1].trim() : '';
}

function stripHtml(html: string): string {
  return html
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '')
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '')
    .replace(/<nav[^>]*>[\s\S]*?<\/nav>/gi, '')
    .replace(/<footer[^>]*>[\s\S]*?<\/footer>/gi, '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// --- Research brief synthesis -----------------------------------------------
//
// The model-callable synthesis step. When the model is offline, synthesis
// returns a skeleton brief that the operator fills in.

export interface SynthesisInput {
  profile: {
    name: string;
    tagline: string;
    industry: string;
    icp: string;
    segments: { name: string; pain: string }[];
    offering: string;
    pricing: string;
    gaps: string[];
  };
  localDocSnippets: string[];
  webResults: WebFetchResult[];
  localDocCount: number;
}

export async function synthesizeResearchBrief(
  input: SynthesisInput,
  _modelApi:
    | { baseUrl: string; model: string }
    | null = null, // pass null when model offline
): Promise<ResearchBriefT> {
  const now = new Date().toISOString();
  const slug = input.profile.name.toLowerCase().replace(/\s+/g, '-');

  // --- Extract competitors from web results ---
  const competitors = extractCompetitorEntries(input.webResults);

  // --- Extract keywords from web results ---
  const keywords = extractKeywordsFromWeb(input.webResults);

  // --- Build content gaps from profile gaps ---
  const contentGaps: z.infer<typeof ContentGap>[] = input.profile.gaps
    .filter((g) => g.length > 10)
    .map((g) => ({
      topic: g,
      whyItMatters: `Customers cannot evaluate or trust HempForge without this information.`,
      competingContent: `[UNVERIFIED] Competitors cover this topic — verify before using.`,
    }));

  // --- Fallback positioning options (used when model is offline) ---
  const positioningOptions: z.infer<typeof PositioningOption>[] = [
    {
      framing: 'Compliance infrastructure for regulated hemp operators',
      tagline: 'Compliance you can prove.',
      targetSegment: input.profile.segments[0]?.name ?? 'Hemp testing labs',
      risks: [
        'Assumes technical buyers who care about audit trails, not just price',
        'Differentiator is invisible on a feature list — needs proof (audit trail screenshot)',
      ],
      confidence: 'low',
    },
    {
      framing: 'Open-source hemp compliance with a real audit chain',
      tagline: 'Open. Auditable. Regulators welcome.',
      targetSegment: 'Compliance consultants and vertically-integrated brands',
      risks: [
        '"Open source" can signal "unfinished" to enterprise buyers',
        'Literature intelligence and decarb kinetics need honest disclaimers',
      ],
      confidence: 'low',
    },
  ];

  const brief: ResearchBriefT = {
    generatedAt: now,
    businessSlug: slug,
    profileStage: input.profile.industry,
    competitorLandscape: competitors,
    keywordOpportunities: keywords,
    contentGaps,
    positioningOptions,
    marketSizing: {
      estimate: '[UNVERIFIED] Hundreds of hemp testing labs in the US; most use spreadsheets or no formal system.',
      basis: '[UNVERIFIED] Estimate based on hemp acreage data and lab density ratios. Verify against USDA/state data.',
      caveats: [
        'Hemp acreage fluctuates year-to-year; lab count tracks cultivation volume',
        'Many states do not publish lab registration counts; estimate is directional only',
        'International markets (EU, Canada) are separate — not included in this estimate',
      ],
    },
    localDocumentsIngested: input.localDocSnippets,
    webSources: input.webResults.map((r) => r.url).filter((u) => !u.startsWith('data:')),
    disclaimer: DISLAIMER,
    operatorNotes: OPERATOR_NOTES,
  };

  return ResearchBrief.parse(brief);
}

function extractCompetitorEntries(webResults: WebFetchResult[]): z.infer<typeof CompetitorEntry>[] {
  const competitors: z.infer<typeof CompetitorEntry>[] = [];
  for (const result of webResults) {
    if (result.error || !result.content) continue;
    const name = result.title || extractDomainName(result.url);
    competitors.push({
      name,
      tagline: '[UNVERIFIED] Tagline not yet confirmed.',
      website: result.url,
      positioning: '[UNVERIFIED] Positioning extracted from page content. Verify.',
      strengths: ['[UNVERIFIED] Add after human review.'],
      weaknesses: ['[UNVERIFIED] Add after human review.'],
      confidence: 'low',
      source: result.url,
    });
  }
  return competitors;
}

function extractKeywordsFromWeb(webResults: WebFetchResult[]): z.infer<typeof KeywordOpportunity>[] {
  const seen = new Set<string>();
  const keywords: z.infer<typeof KeywordOpportunity>[] = [];

  const intentMap: Record<string, z.infer<typeof KeywordOpportunity>['intent']> = {
    coa: 'transactional',
    compliance: 'informational',
    hemp: 'informational',
    lab: 'commercial',
    inspection: 'informational',
    metrc: 'commercial',
    audit: 'informational',
    testing: 'commercial',
    regulation: 'informational',
    certificate: 'transactional',
  };

  for (const result of webResults) {
    const text = result.content.toLowerCase();
    for (const [phrase, intent] of Object.entries(intentMap)) {
      if (text.includes(phrase) && !seen.has(phrase)) {
        seen.add(phrase);
        keywords.push({
          phrase,
          intent,
          difficulty: 'medium',
          volumeHint: '[UNVERIFIED] Volume estimate. Do not publish without research tool data.',
        });
      }
    }
    if (keywords.length >= 10) break;
  }

  // Always include these baseline opportunities from the profile
  const baseline = [
    { phrase: 'hemp testing compliance software', intent: 'commercial' as const, difficulty: 'medium' as const },
    { phrase: 'hemp coa review tool', intent: 'transactional' as const, difficulty: 'easy' as const },
    { phrase: 'hemp lab audit trail', intent: 'informational' as const, difficulty: 'medium' as const },
    { phrase: 'metrc integration software', intent: 'commercial' as const, difficulty: 'hard' as const },
  ];
  for (const kw of baseline) {
    if (!seen.has(kw.phrase)) {
      seen.add(kw.phrase);
      keywords.push({
        ...kw,
        volumeHint: '[UNVERIFIED] Volume estimate. Do not publish without research tool data.',
      });
    }
  }

  return keywords.slice(0, 15);
}

function extractDomainName(url: string): string {
  try {
    const u = new URL(url);
    return u.hostname.replace(/^www\./, '');
  } catch {
    return url.slice(0, 40);
  }
}

// --- Persistence -----------------------------------------------------------

export function saveResearchBrief(
  brief: ResearchBriefT,
  profilesDir: string = 'data/business-profiles',
): string {
  const dir = path.join(profilesDir, brief.businessSlug);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  const filePath = path.join(dir, 'research-brief.json');
  fs.writeFileSync(filePath, JSON.stringify(brief, null, 2), 'utf8');
  return filePath;
}

export function loadResearchBrief(
  slug: string,
  profilesDir: string = 'data/business-profiles',
): ResearchBriefT | null {
  const filePath = path.join(profilesDir, slug, 'research-brief.json');
  if (!fs.existsSync(filePath)) return null;
  try {
    const raw = fs.readFileSync(filePath, 'utf8');
    return ResearchBrief.parse(JSON.parse(raw));
  } catch {
    return null;
  }
}

// --- High-level pipeline runner --------------------------------------------

export interface RunResearchOptions extends ResearchPipelineConfig {
  profileSlug: string;
  profilesDir?: string;
  localRepoPath?: string;
  webSearchUrls?: string[];
  modelApi?: { baseUrl: string; model: string } | null;
}

export async function runResearchPipeline(
  options: RunResearchOptions,
): Promise<{ brief: ResearchBriefT; path: string }> {
  const config = { ...DEFAULT_CONFIG, ...options };
  const profilesDir = config.profilesDir ?? 'data/business-profiles';

  // Load the business profile
  const { loadBusinessProfile } = await import('./businessProfile');
  const profile = loadBusinessProfile(options.profileSlug, profilesDir);

  // Ingest local documents
  const localDocs: IngestResult[] = options.localRepoPath
    ? ingestLocalDocuments(options.localRepoPath, config.localDocExtensions)
    : [];
  const localSnippets = extractRelevantSnippets(localDocs, [
    profile.business.name,
    profile.offering.summary.split(' ')[0],
    ...profile.customer.segments.map((s) => s.name.split(' ')[0]),
  ]);

  // Fetch web pages
  const webUrls = options.webSearchUrls ?? buildDefaultSearchUrls(profile.business.name, profile.offering.summary);
  const webResults = await Promise.allSettled(
    webUrls.slice(0, config.maxWebSources).map((url) =>
      fetchWebPage(url, config.timeoutMs),
    ),
  );
  const validResults = webResults
    .filter((r): r is PromiseFulfilledResult<WebFetchResult> => r.status === 'fulfilled')
    .map((r) => r.value);

  // Synthesize
  const brief = await synthesizeResearchBrief(
    {
      profile: {
        name: profile.business.name,
        tagline: profile.business.tagline,
        industry: profile.business.industry,
        icp: profile.customer.icp,
        segments: profile.customer.segments,
        offering: profile.offering.summary,
        pricing: profile.offering.pricing,
        gaps: profile.gaps,
      },
      localDocSnippets: localSnippets,
      webResults: validResults,
      localDocCount: localDocs.length,
    },
    config.modelApi,
  );

  // Persist
  const outputPath = saveResearchBrief(brief, profilesDir);
  return { brief, path: outputPath };
}

function buildDefaultSearchUrls(name: string, _offering: string): string[] {
  // Build seed URLs from the business name and industry keywords
  const queries = [
    `${name} compliance`,
    'hemp lab compliance software',
    'hemp coa software',
    'hemp testing software',
    'metrc integration hemp',
  ];
  // Use DuckDuckGo HTML lite results as a seed — no API key needed
  return queries.map((q) => `https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`);
}
